### ISSUE TITLE
Write Unit Tests

### ISSUE THREAD

**Issue by josev814** [josev814/UNCFSU-CSC322#4]
Get Unit tests written to test out all of our function calls in NodeJs

**Comment by josev814** [comment]
@infernoj How are the unit tests coming along for you?

**Comment by infernoj** [comment]
> @infernoj How are the unit tests coming along for you?

did the format they had in the vidéo for the unit test
> expect(isPrime(n)).toBe(true);
for the functions: function getPrimes(n), function goldbach().
didnt see where to do it in that spot this thing you created , so made it in a workflow like in the vidéos. but couldnt see where to run the unit test to test it on the goldbach code

**Comment by josev814** [comment]
@infernoj Do you have a branch committed that we could look at?  Thinking once the branch is committed we can look at adding the GitHub actions to run the tests.

**Comment by infernoj** [comment]
> @infernoj Do you have a branch committed that we could look at?  Thinking once the branch is committed we can look at adding the GitHub actions to run the tests.

How to do that? I did a workflow thing

**Comment by josev814** [comment]
@infernoj it looks like we have a branch for writing unit tests.  https://github.com/josev814/UNCFSU-CSC322/tree/4-write-unit-tests.  You can add your files to that branch.

**Comment by infernoj** [comment]
> @infernoj any progress on the unit tests?

Where were the other functions that needed the unit test, I've only seen the two

**Comment by josev814** [comment]
Goldbach still needs tested.  I wrote tests for checking if the max number was set and if prime was returning an expected result.
